# Generated by Django 4.2.2 on 2023-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10)),
                ("prices", models.CharField(max_length=10)),
                ("volume", models.CharField(max_length=10)),
                ("base", models.CharField(max_length=10)),
                ("peak", models.CharField(max_length=10)),
                ("off_peak", models.CharField(max_length=10)),
                ("hour", models.CharField(max_length=5)),
                ("bgn_per_mwh", models.CharField(max_length=10)),
                ("mwh", models.CharField(max_length=10)),
            ],
        ),
    ]
