# Generated by Django 4.2.2 on 2023-06-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="csvdata",
            table="csv_data",
        ),
    ]
