# Generated by Django 4.2.2 on 2023-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_csvdata_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvdata",
            name="base",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="bgn_per_mwh",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="mwh",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="off_peak",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="peak",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="prices",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="volume",
        ),
        migrations.AddField(
            model_name="csvdata",
            name="price_bgn_mwh",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="volume_mwh",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="csvdata",
            name="date",
            field=models.DateField(),
        ),
    ]
