# Generated by Django 4.2.2 on 2023-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_csvdata_base_remove_csvdata_bgn_per_mwh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvdata",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
