# Generated by Django 4.2.2 on 2023-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_csvdata_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvdata",
            name="price_bgn_mwh",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="volume_mwh",
        ),
        migrations.AddField(
            model_name="csvdata",
            name="base",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="bgn_per_mwh",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="hour",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="mwh",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="off_peak",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="peak",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="prices",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="volume",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="csvdata",
            name="date",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
